parameters:
  - name: buildConfig
    displayName: Build Configuration to Use
    default: Debug
    values:
    - Debug
    - Release

trigger: none # https://aka.ms/obpipelines/triggers

variables:
- name: buildConfiguration
  value: ${{ parameters.buildConfig }}
- name: CDP_DEFINITION_BUILD_COUNT
  value: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
- name: WindowsContainerImage
  value: 'onebranch.azurecr.io/windows/ltsc2022/vse2022:latest' # Docker image which is used to build the project https://aka.ms/obpipelines/containers

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    featureFlags:
      WindowsHostVersion:
        Version: 2022
      EnableCDPxPAT: false
    cloudvault: # https://aka.ms/obpipelines/cloudvault
      enabled: false
    globalSdl: # https://aka.ms/obpipelines/sdl
      # tsa:
      #  enabled: false # onebranch publish all sdl results to TSA. If TSA is disabled all SDL tools will forced into 'break' build mode.
      # credscan:
      #   suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
      policheck:
        break: false # always break the build on policheck issues. You can disable it by setting to 'false'
      # suppression:
      #   suppressionFile: $(Build.SourcesDirectory)\.gdn\global.gdnsuppress
    nugetPublishing:
      feeds:
        - name: Official
          files_to_publish: '*.nupkg'
          continueOnConflict: false
    stages:
    - stage: build
      jobs:
      - job: main
        pool:
          type: windows  # read more about custom job pool types at https://aka.ms/obpipelines/yaml/jobs

        variables: # More settings at https://aka.ms/obpipelines/yaml/jobs
          ob_outputDirectory: '$(Build.SourcesDirectory)\out' # this directory is uploaded to pipeline artifacts, reddog and cloudvault. More info at https://aka.ms/obpipelines/artifacts
          # https://aka.ms/obpipelines/sdl
          ob_sdl_binskim_break: false # always break the build on binskim issues, even if TSA enabled. You can disable it by setting to 'false'
          ob_sdl_roslyn_break: false
          ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}: # conditionally enable symbolsPublishing for master branch only
            ob_symbolsPublishing_enabled: true # https://aka.ms/obpipelines/symbols
          # ob_sdl_suppression_suppressionFile: $(Build.SourcesDirectory)\.gdn\job.gdnsuppress
          ${{ if eq('true', 'true') }}:
            ob_nugetPublishing_enabled: true
        steps:
        - checkout: self

        - task: UseDotNet@2
          displayName: 'Install .NET SDK'
          inputs:
            packageType: 'sdk'
            version: '9.x'
            includePreviewVersions: true
            installationPath: $(Agent.ToolsDirectory)/dotnet
        
        - task: NuGetToolInstaller@1

        - task: NuGetAuthenticate@1
          inputs:
            forceReinstallCredentialProvider: true

        - task: onebranch.pipeline.version@1 # generates automatic version. For other versioning options check https://aka.ms/obpipelines/versioning
          displayName: 'Setup BuildNumber'  
          inputs:
            system: 'RevisionCounter'
            major: '1'
            minor: '0'
            exclude_commit: true

        - task: PowerShell@2
          displayName: 'Configure NuGet SSL Settings'
          inputs:
            targetType: 'inline'
            script: |
              # Set environment variables for SSL handling
              [Environment]::SetEnvironmentVariable("DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER", "0", "Process")
              [Environment]::SetEnvironmentVariable("NUGET_CERT_REVOCATION_MODE", "offline", "Process")
              [Environment]::SetEnvironmentVariable("DOTNET_SKIP_FIRST_TIME_EXPERIENCE", "true", "Machine")
              
              # Configure NuGet sources
              nuget sources clear
              nuget sources add -name "nuget.org" -source "https://api.nuget.org/v3/index.json"
              
              # List sources to verify
              nuget sources list

              #restore DLL project to verify SSL settings
              [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
              nuget restore '$(Build.SourcesDirectory)\AzFilesSmbMIClient\Windows\dotnet\dll\Microsoft.Azure.AzFilesSmbMI.csproj'

        - task: PowerShell@2
          displayName: 'Restore EXE Project SSL Settings'
          inputs:
            targetType: 'inline'
            script: |
              [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
              
              # Add the nuget.org source
              dotnet restore '$(Build.SourcesDirectory)\AzFilesSmbMIClient\Windows\exe\AzFilesSmbMIClient.csproj'

        - task: DotNetCoreCLI@2
          displayName: 'Restore EXE packages'
          inputs:
            command: 'restore'
            projects: '$(Build.SourcesDirectory)\AzFilesSmbMIClient\Windows\exe\AzFilesSmbMIClient.csproj'
            feedsToUse: 'select'
            includeNuGetOrg: true
            noCache: true
            verbosityRestore: 'Normal'
          env:
            DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER: 0
            NUGET_CERT_REVOCATION_MODE: offline

        - task: DotNetCoreCLI@2
          displayName: 'Build EXE Project'
          inputs:
            command: build
            versioningScheme: byBuildNumber
            arguments: '--configuration $(BuildConfiguration)'
            projects: '$(Build.SourcesDirectory)\AzFilesSmbMIClient\Windows\exe\AzFilesSmbMIClient.csproj'

        - task: onebranch.pipeline.signing@1
          displayName: 'Sign NuGet Package Binaries'
          inputs:
            command: 'sign'
            signing_profile: 'external_distribution' # https://eng.ms/docs/products/onebranch/signing/containerbuildsigning#signing_profile
            files_to_sign: '**/*.exe,**/*.dll'
            search_root: '$(Build.SourcesDirectory)\windows\exe\bin\$(buildConfiguration)\net472'