parameters:
  - name: buildConfig
    displayName: Build Configuration to Use
    default: Debug
    values:
    - Debug
    - Release

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- name: buildConfiguration
  value: ${{ parameters.buildConfig }}

steps:
- checkout: self

- task: UseDotNet@2
  displayName: Setup .NET SDK Version 9.x
  inputs:
    packageType: sdk
    version: 9.x
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'Build the Assembly'
  inputs:
    command: build
    versioningScheme: byBuildNumber
    arguments: '--configuration $(BuildConfiguration)'
    projects: $(Build.SourcesDirectory)/Windows/exe/AzFilesSmbMIClient.csproj

- task: EsrpCodeSigning@3
  displayName: 'Sign Binary Files'
  inputs:
    ConnectedServiceName: 'ESRP CodeSign'
    FolderPath: '$(Build.SourcesDirectory)'
    Pattern: '**/*.exe,**/*.dll'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
        [
          {
              "keyCode": "CP-230012",
              "operationSetCode": "SigntoolSign",
              "parameters": [
              {
                  "parameterName":"FileDigest",
                  "parameterValue":"/fd \"SHA256\""
              },
              {
                  "parameterName": "OpusName",
                  "parameterValue": "Microsoft"
              },
              {
                  "parameterName": "OpusInfo",
                  "parameterValue": "http://www.microsoft.com"
              },
              {
                  "parameterName": "PageHash",
                  "parameterValue": "/NPH"
              },
              {
                  "parameterName":"TimeStamp",
                  "parameterValue":"/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
              }
              ],
              "toolName": "sign",
              "toolVersion": "1.0"
          },
          {
              "keyCode": "CP-230012",
              "operationSetCode": "SigntoolVerify",
              "parameters": [ ],
              "toolName": "sign",
              "toolVersion": "1.0"
          }
        ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'